"""exchange_rate table

Revision ID: ddcdbafd84c3
Revises:
Create Date: 2025-10-24 19:16:07.584486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddcdbafd84c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cur_id", sa.Integer(), nullable=False),
        sa.Column("cur_abbreviation", sa.String(length=3), nullable=False),
        sa.Column("cur_scale", sa.Integer(), nullable=False),
        sa.Column("cur_name", sa.String(length=128), nullable=True),
        sa.Column(
            "cur_official_rate", sa.Numeric(precision=19, scale=4), nullable=False
        ),
        sa.Column("cur_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange_rate")
    # ### end Alembic commands ###
