"""exchange.rate datatype fix

Revision ID: bd105b2ff925
Revises: e36091857154
Create Date: 2025-10-30 16:05:43.413284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd105b2ff925"
down_revision: Union[str, Sequence[str], None] = "e36091857154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange",
        "rate",
        existing_type=sa.NUMERIC(precision=19, scale=28),
        type_=sa.Numeric(precision=47, scale=28),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchange",
        "rate",
        existing_type=sa.Numeric(precision=47, scale=28),
        type_=sa.NUMERIC(precision=19, scale=28),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
