"""Exchange table with transactions and their statuses

Revision ID: e36091857154
Revises: ddcdbafd84c3
Create Date: 2025-10-29 19:47:36.808727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e36091857154"
down_revision: Union[str, Sequence[str], None] = "ddcdbafd84c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_cur_abbreviation", sa.String(length=3), nullable=False),
        sa.Column("target_cur_abbreviation", sa.String(length=3), nullable=True),
        sa.Column("source_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("rate", sa.Numeric(precision=19, scale=28), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CANCELED", "CONFIRMED", name="exchange_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Minsk', now())"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('Europe/Minsk', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange")
    # MANUALLY ADDED INSTRUCTION TO FIX DOWNGRADING ISSUE WITH ENUMS IN ALEMBIC
    op.execute("DROP TYPE IF EXISTS exchange_status;")
    # ### end Alembic commands ###
